version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: meupet_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meupet_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - meupet-network

  nginx: # Novo nome do serviço
    build: ./nginx # Aponte para a pasta onde você criou o Dockerfile e nginx.conf
    container_name: meupet_nginx_gateway
    restart: always
    ports:
      - "8000:8000" # Mapeia a porta 8000 do host para a porta 8000 do container
    networks:
      - meupet-network
    # healthcheck: (Opcional, você pode adicionar um healthcheck simples para o NGINX)
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/nginx_status"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

networks:
  meupet-network:
    external: true

volumes:
  postgres_data: